<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>

    <PackageReadmeFile>Readme.Azure.StorageAccount.md</PackageReadmeFile>
	</PropertyGroup>
  
	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.25.0" />
		<PackageReference Include="GitVersion.MsBuild" Version="6.5.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Framework\OoBDev.Documents.Abstractions\OoBDev.Documents.Abstractions.csproj" />
		<ProjectReference Include="..\..\..\Framework\OoBDev.Extensions\OoBDev.Extensions.csproj" />
		<ProjectReference Include="..\..\..\Framework\OoBDev.MessageQueueing.Abstractions\OoBDev.MessageQueueing.Abstractions.csproj" />
		<ProjectReference Include="..\..\..\Framework\OoBDev.Search.Abstractions\OoBDev.Search.Abstractions.csproj" />
		<ProjectReference Include="..\..\..\Framework\OoBDev.System.Abstractions\OoBDev.System.Abstractions.csproj" />
	</ItemGroup>
</Project>
