<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	  <Nullable>enable</Nullable>
	  <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OoBDev.Amazon.Sqs\OoBDev.Amazon.Sqs.csproj" />
    <ProjectReference Include="..\OoBDev.ComplexEvents.Common\OoBDev.ComplexEvents.Common.csproj" />
    <ProjectReference Include="..\OoBDev.DocumentCenter\OoBDev.DocumentCenter.csproj" />
    <ProjectReference Include="..\OoBDev.MessageQueueing\OoBDev.MessageQueueing.csproj" />
    <ProjectReference Include="..\OoBDev.TestUtilities\OoBDev.TestUtilities.csproj" />
    <ProjectReference Include="..\OoBDev.Toolkit\OoBDev.Toolkit.csproj" />
  </ItemGroup>

</Project>
