<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
		<PackageReference Include="Azure.Messaging.EventHubs" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Net.Http.Headers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OoBDev.ComplexEvents.Contracts\OoBDev.ComplexEvents.Contracts.csproj" />
    <ProjectReference Include="..\OoBDev.IdentityModel.Contracts\OoBDev.IdentityModel.Contracts.csproj" />
    <ProjectReference Include="..\OoBDev.Toolkit.Contracts\OoBDev.Toolkit.Contracts.csproj" />
  </ItemGroup>

</Project>
