#!/usr/bin/env python3
"""Generate the per-project catalog under docs/patterns-discovery/07-project-catalog.

One file per layer folder in src (Common, Framework, Extensions, ExternalServices, Tools, Examples), one table row
per non-test project: name, purpose (first sentence of README.{Project}.md when present), readme and tests flags.
Then run scripts/docs/build-index.py on the output folder to add navigation and the index lists.

Usage: python scripts/docs/build-project-catalog.py
Idempotent and deterministic. Purposes come from the readme; a blank purpose means the project has no readme text.
"""
import io
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'docs', 'patterns-discovery', '07-project-catalog')
LAYERS = ['Common', 'Framework', 'Extensions', 'ExternalServices', 'Tools', 'Examples', 'Spikes']
NL = chr(10)
SKIP = {'bin', 'obj', 'node_modules'}


def projects(layer):
    found = []
    base = os.path.join(SRC, layer)
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP)
        for f in filenames:
            if f.endswith('.csproj'):
                found.append((dirpath, f[:-len('.csproj')]))
    return sorted(found, key=lambda x: x[1].lower())


def purpose(dirpath, name):
    for cand in ('README.%s.md' % name[len('OoBDev.'):] if name.startswith('OoBDev.') else None,
                 'README.%s.md' % name, 'README.md', 'readme.md'):
        if not cand:
            continue
        for base in (dirpath, os.path.dirname(dirpath)):
            p = os.path.join(base, cand)
            if os.path.exists(p) and (base == dirpath or cand.startswith('README.' + name)):
                return read_summary(p), True
    return '', False


def read_summary(path):
    text = io.open(path, encoding='utf-8-sig').read().replace('\r', '')
    text = re.sub(r'<!--.*?-->', '', text, flags=re.S)
    text = re.sub(r'```.*?```', '', text, flags=re.S)
    for para in re.split(r'\n\s*\n', text):
        lines = [l.strip() for l in para.split(NL) if l.strip()]
        if not lines or lines[0].startswith(('#', '|', '-', '*', '>', '!', '[!', '<')):
            continue
        s = re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', ' '.join(lines))
        s = s.replace('|', '/').replace('`', '')
        m = re.match(r'(.{20,220}?[.!?])(\s|$)', s)
        return (m.group(1) if m else s[:200]).strip()
    return ''


def is_test(name):
    return name.endswith('.Tests') or '.Tests.' in name or name.endswith('.Test')


def main():
    os.makedirs(OUT, exist_ok=True)
    total = 0
    for i, layer in enumerate(LAYERS, 1):
        allp = projects(layer)
        names = {n for _, n in allp}
        prods = [(d, n) for d, n in allp if not is_test(n)]
        rows = []
        for d, n in prods:
            desc, has_readme = purpose(d, n)
            stem = n[:-len('.Abstractions')] if n.endswith('.Abstractions') else n
            has_tests = any(t.startswith(stem + '.Tests') or t == stem + 'Tests' for t in names)
            flags = []
            if not has_readme:
                flags.append('no readme')
            if not has_tests and layer == 'Framework' and not n.endswith('.Abstractions'):
                flags.append('no tests project')
            rows.append('| `%s` | %s | %s |' % (n, desc or ' ', ', '.join(flags) or ' '))
        total += len(prods)
        out = [
            '# %s Layer' % layer, '',
            'Generated by `scripts/docs/build-project-catalog.py` from `src/%s`; do not edit by hand. '
            'Purpose is the first sentence of the project readme. Flags mark owner-review items '
            '(a Framework project without a tests project or a project without a readme).' % layer, '',
            '%d projects (test projects excluded).' % len(prods), '',
            '**Table %d — %s projects**' % (i, layer), '',
            '| Project | Purpose | Review flags |', '|---------|---------|--------------|',
        ] + rows + ['']
        io.open(os.path.join(OUT, '%02d-%s.md' % (i, layer.lower())), 'w', encoding='utf-8', newline='').write(NL.join(out))
    readme = os.path.join(OUT, 'README.md')
    if not os.path.exists(readme):
        intro = [
            '# 07 — Project Catalog', '',
            'One line per project, grouped by layer ([architecture](../01-architecture/README.md)). Generated from the source tree, '
            'so it stays current: run `python scripts/docs/build-project-catalog.py` and then `python scripts/docs/build-index.py '
            'docs/patterns-discovery/07-project-catalog`. Flags are owner-review items recorded in [`TODO.md`](../../../TODO.md).', '',
            '<!-- toc:start -->', '<!-- toc:end -->', '']
        io.open(readme, 'w', encoding='utf-8', newline='').write(NL.join(intro))
    print('catalog: %d projects in %d layers' % (total, len(LAYERS)))


if __name__ == '__main__':
    main()
