<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>false</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackAsTool>true</PackAsTool>
		<ToolCommandName>templateengine</ToolCommandName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GitVersion.MsBuild" Version="6.5.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\ExternalServices\Handlebars\OoBDev.Handlebars\OoBDev.Handlebars.csproj" />
    <ProjectReference Include="..\..\Framework\OoBDev.Extensions\OoBDev.Extensions.csproj" />
    <ProjectReference Include="..\..\Framework\OoBDev.System\OoBDev.System.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="*.hbs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="*.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
