<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>false</ImplicitUsings>
		<Nullable>enable</Nullable>
		
		
		
		
    <PackageReadmeFile>Readme.System.Abstractions.md</PackageReadmeFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>		
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="OoBDev.System" />
		<InternalsVisibleTo Include="OoBDev.System.Tests" />
		<InternalsVisibleTo Include="OoBDev.System.Linq" />
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.0.2" />
   
    <PackageReference Include="GitVersion.MsBuild" Version="6.5.1">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
