<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>false</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<PackageReadmeFile>ReadMe.AspNetCore.JwtAuthentication.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GitVersion.MsBuild" Version="6.5.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OoBDev.AspNetCore.Mvc\OoBDev.AspNetCore.Mvc.csproj" />
    <ProjectReference Include="..\OoBDev.Identity.Abstractions\OoBDev.Identity.Abstractions.csproj" />
  </ItemGroup>
</Project>
