
DROP FUNCTION [vector].[Random]
DROP FUNCTION [vector].[RandomF]
DROP FUNCTION [vector].[Uniform]
DROP FUNCTION [vector].[UniformF]
DROP FUNCTION [vector].[Element]
DROP FUNCTION [vector].[ElementF]
DROP FUNCTION [vector].[Magnitude]
DROP FUNCTION [vector].[MagnitudeF]
DROP FUNCTION [vector].[Length]
DROP FUNCTION [vector].[LengthF]
DROP FUNCTION [vector].[Distance]
DROP FUNCTION [vector].[DistanceF]
DROP FUNCTION [vector].[Midpoint]
DROP FUNCTION [vector].[MidpointF]
DROP FUNCTION [vector].[Angle]
DROP FUNCTION [vector].[AngleF]
DROP AGGREGATE [vector].[Centroid]
DROP AGGREGATE [vector].[CentroidF] 
DROP TYPE [vector].[VectorD] 
DROP TYPE [vector].[VectorF] 
DROP ASSEMBLY [OoBDev.Data.Vectors]
DROP SCHEMA [vector]
GO