<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>false</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GitVersion.MsBuild">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MailKit" />

		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="OoBDev.MailKit.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Framework\OoBDev.Communications.Abstractions\OoBDev.Communications.Abstractions.csproj" />
	</ItemGroup>

</Project>
