<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>false</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\..\Framework\**\*.AspnetCore.*\ReadMe.*.md" Pack="true">
			<Link>%(Filename)%(Extension)</Link>
			<PackagePath>\%(Filename)%(Extension)</PackagePath>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
		
	<ItemGroup>
		<ProjectReference Include="..\..\Framework\**\OoBDev.AspNetCore.*.csproj" />
		<ProjectReference Remove="..\..\Framework\**\OoBDev.*.Tests.csproj" />
	</ItemGroup>
		
	<ItemGroup>
	  <PackageReference Include="GitVersion.MsBuild" Version="6.5.1">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>
		
</Project>
