<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>false</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Retro\Apple2\Dos33\1983_dos33c.dsk" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Retro\Apple2\Dos33\1983_dos33c.dsk" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="GitVersion.MsBuild" Version="6.8.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="Moq" Version="4.21.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.4.1" />
		<PackageReference Include="MSTest.TestFramework" Version="4.4.1" />
		<PackageReference Include="coverlet.collector" Version="10.1.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\OoBDev.System.IO.Pipelines\OoBDev.System.IO.Pipelines.csproj" />
	  <ProjectReference Include="..\OoBDev.System.IO.Ports\OoBDev.System.IO.Ports.csproj" />
	  <ProjectReference Include="..\OoBDev.System.IO.UsbHids\OoBDev.System.IO.UsbHids.csproj" />
	  <ProjectReference Include="..\OoBDev.System\OoBDev.System.csproj" />
	  <ProjectReference Include="..\OoBDev.TestUtilities\OoBDev.TestUtilities.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Math\" />
	</ItemGroup>

</Project>
