<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		
		<PackageReadmeFile>Readme.AzureServiceBus.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GitVersion.MsBuild" Version="6.5.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Framework\OoBDev.MessageQueueing.Abstractions\OoBDev.MessageQueueing.Abstractions.csproj" />
		<ProjectReference Include="..\..\..\Framework\OoBDev.System.Abstractions\OoBDev.System.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Readme.AzureServiceBus.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
